import type { Metadata } from 'next';
import './globals.css';
import Layout from '@/components/MainLayout';

export const metadata: Metadata = {
  title: 'K LE DORTZ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-black">
        <Layout children={children} />
      </body>
    </html>
  );
}
